### ISSUE TITLE
Dont Playing

### ISSUE THREAD

**Issue by Tinoxy** [Kingdread/floppymusic#11]
Hey i read all the Issues but i dont fine it out.

I use a Pi Zero w1.1 but is not working.

Can one help me out?

**Comment by Kingdread** [comment]
Hey, unfortunately I don't have a Pi Zero myself to test it, but have you tried compiling with `make MODEL=PI2` to see if that fixes it?

**Comment by Tinoxy** [comment]
after a new insall from the Os i working now. idk why ^^.

But Thanks for the Help.
